# Generated by Django 5.1 on 2024-08-26 01:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_todo_id_alter_todo_time_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='todos',
        ),
    ]
