# Generated by Django 5.0.2 on 2024-09-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_customersresetsid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersresetsid',
            old_name='created_when',
            new_name='created',
        ),
    ]
